### ISSUE TITLE
rackunit, redex, scribble helpers

### ISSUE THREAD

**Issue by bennn** [mbutterick/sugar#19]
I have some helper functions that I like to use for rackunit, redex, and scribble.

- https://pkgd.racket-lang.org/pkgn/package/rackunit-abbrevs
- https://pkgd.racket-lang.org/pkgn/package/redex-abbrevs
- https://pkgd.racket-lang.org/pkgn/package/scribble-abbrevs

I used the `-abbrevs` suffix because it made sense for RackUnit and I didn't think of anything better for the others.

Today I was thinking, `sugar/rackunit` etc. would be better names.

How do you feel about either:
- adding those packages' code to this repo,
- or changing those packages to multi collections, so installing `rackunit-abbrevs` installs a `sugar/rackunit` (like how some packages add to the `typed/` collection)

(I'd prefer option 2 and I guess I could just do it, but I want to ask permission.)

**Comment by mbutterick** [comment]
> adding those packages' code to this repo

Though MB of the [past suggested](https://github.com/mbutterick/sugar/issues/14) that I would be open to this, today I think that creates an expectation that I will support / maintain the code.

So like you I prefer option #2:

> so installing rackunit-abbrevs installs a sugar/rackunit

Which is fine.
