### ISSUE TITLE
switch to MIT license

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/sugar#20]
@AlexKnauth 
@samth 
@lijunsong 

Consistent with [Racket’s overall relicensing](https://blog.racket-lang.org/2019/11/completing-racket-s-relicensing-effort.html) from LGPL to Apache+MIT, I’d like to move Sugar from LGPL to MIT.

Because the MIT license is more permissive, this requires the assent of you, the esteemed contributors.

If you agree, please post a message saying so, e.g. — "I hereby relicense my contributions to Sugar under the MIT license."

On January 1, if you have not agreed to the relicensing, I will remove your code. Thanks.

**Comment by AlexKnauth** [comment]
I hereby relicense my contributions to Sugar under the MIT license.

**Comment by lijunsong** [comment]
I hereby relicense my contributions to Sugar under the MIT license.

**Comment by mbutterick** [comment]
Closed by 3ce9a7c650e87814eeccc23dc63753b6a94be7b0
