### ISSUE TITLE
#lang sugar/debug does not export identifiers to REPL

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/sugar#9]
```racket
#lang sugar/debug racket
(provide (all-defined-out))
(define foo 42)

> foo
foo: undefined;
 cannot reference an identifier before its definition
```

**Comment by AlexKnauth** [comment]
This works fine for me ... ??

**Comment by AlexKnauth** [comment]
Oh! I think it's to do with hygiene in the new macro expander vs. the old one. 
I just tried it with 6.1.1 and got that error, but it works with the new macro expander in a recent snapshot. It still works fine within modules, but I think the repl is off by a syntax-mark or something. 
I think I have an idea of how to fix it, and I'll try making a pull request.
